# Instructions:
# - Read the options, get to know them.
# - Once options are edited, rename this file to config.yml
# - Make sure this is only run when you are fully finished preparing your files for release.
#   This includes stuff like preparing global tags, container metadata, folder structure, file and folder names.
# - Take a small quick crash course on YAML to make sure you don't mess up the values mistakenly.

file: C:/path/to/the/release/and-its-file.mkv
art: rpg  # artwork template
template: season  # nfo template
preview: https://imgbox.com/g/.....  # I recommend 4 screens, 350x350 resized, release-name for gallery name
source: R2 GBR Anchor Bay Ent. DVD-PHOENiX (Thanks!!)  # source, try give credit
note: ~  # special information, notices, etc.

# db ids are attempted to be fetched from meta tags, set values will be ignored if found
imdb: tt0439341
tmdb: tv/4355
tvdb: 75444

# TV only:
fanart_api_key: ~  # key is needed for TV titles, probably won't do anything for Movies
season: 1
episodes: 12
episode: 1
episode-name: Don Giovanni, Dramma giocoso en deux actes

# Important information for TV:
# - Release name is gotten from the parent folder name, not the file name.
# - The code automatically gets episode count by counting neighbouring files of the same file-ext.
# - Episode and Episode-name should *NOT* be set if it's a Season/TV Pack.
# - If it's a TV pack of no specific season, you may change season from a number to e.g. "Pack".
